// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

import {Script, console2} from "forge-std/Script.sol";
import {IArcPet} from "../src/interfaces/IArcPet.sol";
import {PetRenderer} from "../src/PetRenderer.sol";

/// @notice Dumps sample SVGs + one metadata JSON to docs/samples/ for human review. Pure rendering, no RPC, no tx.
/// @dev Run from contracts/: `forge script script/RenderSamples.s.sol` (or `pnpm contracts:samples`).
///      Writes: <species>-<mood>.svg for 4 species x 5 moods, eyes-<n>.svg, palette-<n>.svg, hostile-name.svg,
///      metadata-sample.json and index.html (a gallery of all of them).
contract RenderSamples is Script {
    string internal constant DIR = "../docs/samples/";
    uint64 internal constant T0 = 1_790_000_000;

    string internal gallery;

    function run() external {
        string[5] memory moods = ["egg", "happy", "hungry", "sad", "tomb"];
        for (uint8 s; s < 4; ++s) {
            string memory species = PetRenderer.speciesName(s);
            for (uint8 m; m < 5; ++m) {
                string memory file = string.concat(_lower(species), "-", moods[m], ".svg");
                _write(file, PetRenderer.svg(_pet(s, s * 2, s, IArcPet.Mood(m), species)));
            }
        }
        for (uint8 e; e < 4; ++e) {
            _write(
                string.concat("eyes-", vm.toString(e), ".svg"),
                PetRenderer.svg(_pet(0, 2, e, IArcPet.Mood.Happy, PetRenderer.eyesName(e)))
            );
        }
        for (uint8 pal; pal < 8; ++pal) {
            _write(
                string.concat("palette-", vm.toString(pal), ".svg"),
                PetRenderer.svg(_pet(1, pal, 0, IArcPet.Mood.Happy, PetRenderer.paletteName(pal)))
            );
        }
        _write("hostile-name.svg", PetRenderer.svg(_pet(3, 5, 1, IArcPet.Mood.Sad, "<b>\"Tom\" & 'Jerry'")));

        IArcPet.PetInfo memory sample = _pet(1, 3, 1, IArcPet.Mood.Happy, "Mochi");
        vm.writeFile(string.concat(DIR, "metadata-sample.json"), PetRenderer.metadata(42, sample, sample.asOf));

        vm.writeFile(
            string.concat(DIR, "index.html"),
            string.concat(
                "<!doctype html><meta charset=utf-8><title>ArcPet samples</title>",
                "<style>body{font:14px monospace;background:#fafafa}figure{display:inline-block;margin:8px}",
                "img{width:180px;height:180px;image-rendering:pixelated;border:1px solid #ddd}</style>",
                "<h1>ArcPet renderer samples</h1><p>Generated by contracts/script/RenderSamples.s.sol</p>",
                gallery
            )
        );
        console2.log("samples written to docs/samples/");
    }

    function _write(string memory file, string memory svg) internal {
        vm.writeFile(string.concat(DIR, file), svg);
        gallery = string.concat(
            gallery,
            '<figure><img src="',
            file,
            '"><figcaption>',
            file,
            " (",
            vm.toString(bytes(svg).length),
            " B)</figcaption></figure>"
        );
    }

    function _pet(uint8 species, uint8 palette, uint8 eyes, IArcPet.Mood mood, string memory name)
        internal
        pure
        returns (IArcPet.PetInfo memory p)
    {
        p.id = 42;
        p.name = name;
        p.asOf = T0 + 5 days;
        p.mood = mood;
        if (mood == IArcPet.Mood.Egg) {
            p.status = IArcPet.Status.Egg;
            p.hunger = 100;
            p.happiness = 100;
            return p;
        }
        p.species = species;
        p.palette = palette;
        p.eyes = eyes;
        p.bornAt = T0;
        p.status = IArcPet.Status.Alive;
        p.age = 5 days;
        p.hunger = mood == IArcPet.Mood.Hungry ? 15 : 85;
        p.happiness = mood == IArcPet.Mood.Sad ? 20 : 70;
        if (mood == IArcPet.Mood.Tomb) {
            p.status = IArcPet.Status.Buried;
            p.hunger = 0;
            p.happiness = 0;
            p.deathAt = T0 + 4 days;
            p.diedAt = p.deathAt;
            p.age = 4 days;
        }
    }

    function _lower(string memory s) internal pure returns (string memory) {
        bytes memory b = bytes.concat(bytes(s)); // copy: bytes(s) aliases the caller's string
        for (uint256 i; i < b.length; ++i) {
            if (b[i] >= "A" && b[i] <= "Z") b[i] = bytes1(uint8(b[i]) + 32);
        }
        return string(b);
    }
}
