#!/usr/bin/env node
// Generates the typed ABI modules in src/abi/ from the Foundry artifacts in contracts/out:
//   ArcPet.ts               <- contracts/src/ArcPet.sol
//   ArcDrawCoordinator.ts   <- contracts/src/vendor/arcdraw/interfaces/IArcDrawCoordinator.sol (the vendored interface)
// src/abi/ holds generated files only (biome skips it).
//
//   pnpm contracts:abi                         # forge build + write src/abi/*.ts
//   pnpm --filter @arcpet/sdk generate:abi     # write them from the current artifacts (run `forge build` first)
//   pnpm --filter @arcpet/sdk check:abi        # exit 1 if a committed module does not match its artifact
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sdkDir = resolve(here, '..');
const repoDir = resolve(sdkDir, '../..');
const check = process.argv.includes('--check');
const show = (path) => relative(repoDir, path);

const targets = [
  { artifact: 'ArcPet.sol/ArcPet.json', module: 'ArcPet.ts', exportName: 'arcPetAbi' },
  {
    artifact: 'IArcDrawCoordinator.sol/IArcDrawCoordinator.json',
    module: 'ArcDrawCoordinator.ts',
    exportName: 'arcDrawCoordinatorAbi',
  },
];

let failed = false;
for (const t of targets) {
  const artifactPath = resolve(repoDir, 'contracts/out', t.artifact);
  const modulePath = resolve(sdkDir, 'src/abi', t.module);
  const hasArtifact = existsSync(artifactPath);
  const hasModule = existsSync(modulePath);

  if (!hasArtifact && !hasModule) {
    console.log(`not built yet (no ${show(artifactPath)}, no ${show(modulePath)}): nothing to do`);
    continue;
  }
  if (!hasArtifact) {
    console.error(
      `missing ${show(artifactPath)} while ${show(modulePath)} exists; run \`forge build\` in contracts/`,
    );
    failed = true;
    continue;
  }

  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  const content =
    '// AUTO-GENERATED by packages/sdk/scripts/generate-abi.mjs from contracts/out. Do not edit.\n' +
    '// Regenerate: pnpm contracts:abi\n\n' +
    `export const ${t.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  const current = hasModule ? readFileSync(modulePath, 'utf8') : null;
  if (current === content) {
    console.log(`${show(modulePath)} is up to date`);
    continue;
  }
  if (check) {
    const reason = current === null ? 'is missing' : 'is stale';
    console.error(`${show(modulePath)} ${reason} for ${show(artifactPath)}; run \`pnpm contracts:abi\``);
    failed = true;
    continue;
  }
  mkdirSync(dirname(modulePath), { recursive: true });
  writeFileSync(modulePath, content);
  console.log(`wrote ${show(modulePath)}`);
}
process.exit(failed ? 1 : 0);
